const ITEMS=window.KNOWLEDGE_ITEMS||[];
const STORE='zsb-knowledge-v26-day1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const isQuestion=i=>i?.studyMode==='question'||String(i?.recordType||'').includes('题目');
const isNote=i=>!isQuestion(i)&&(i?.studyMode==='note'||String(i?.recordType||'').includes('笔记'));
const NOTES=ITEMS.filter(isNote).sort((a,b)=>(a.order||0)-(b.order||0));
const KNOWLEDGE=ITEMS.filter(i=>!isNote(i)&&!String(i.recordType||'').includes('PDF'));
let data=load(),state={subject:'',chapter:'',source:'',date:'',status:'',q:'',selected:''};
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'{}');x.study||={};return x}catch{return{study:{}}}}
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function st(id){return data.study?.[id]||{read:false,starred:false,note:''}}
function parts(i){return String(i.chapter||'未分章').split('｜').map(x=>x.trim()).filter(Boolean)}
function rootKey(i){const p=parts(i);return `${i.subject||p[0]||'未分类'}|||${p[1]||p[0]||'未分章'}`}
function rootTitle(i){const p=parts(i);return p[1]||p[0]||'未分章'}
function section(i){const p=parts(i);return p.length>2?p.slice(2).join('｜'):(p[1]||'本章内容')}
function source(i){return i.sourceOrg||'未标注'}
function date(i){return i.importDate||''}
function dateLabel(i){return i.importLabel||i.range||date(i)||'未记录日期'}
function searchText(i){return [i.title,i.subject,i.chapter,i.category,i.oneLine,i.sourceOrg,i.importLabel,...(i.keywords||[]),...(i.basicExplain||[]),...(i.mustPatterns||[])].join(' ').toLowerCase()}
function filtered(){return NOTES.filter(i=>{const s=st(i.id);if(state.subject&&i.subject!==state.subject)return false;if(state.chapter&&rootKey(i)!==state.chapter)return false;if(state.source&&source(i)!==state.source)return false;if(state.date&&date(i)!==state.date)return false;if(state.status==='unread'&&s.read)return false;if(state.status==='read'&&!s.read)return false;if(state.status==='starred'&&!s.starred)return false;return !state.q||searchText(i).includes(state.q.toLowerCase())})}
function uniq(a){return [...new Set(a.filter(Boolean))]}
function fillFilters(){const subjects=uniq(NOTES.map(i=>i.subject));$('#subjectFilter').innerHTML='<option value="">全部学科</option>'+subjects.map(x=>`<option>${esc(x)}</option>`).join('');const chapters=new Map();NOTES.filter(i=>!state.subject||i.subject===state.subject).forEach(i=>chapters.set(rootKey(i),`${i.subject} · ${rootTitle(i)}`));$('#chapterFilter').innerHTML='<option value="">全部章节</option>'+[...chapters.entries()].map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join('');const sources=uniq(NOTES.map(source));$('#sourceFilter').innerHTML='<option value="">全部机构</option>'+sources.map(x=>`<option>${esc(x)}</option>`).join('');const dates=uniq(NOTES.map(date)).sort();$('#dateFilter').innerHTML='<option value="">全部日期</option>'+dates.map(x=>`<option value="${esc(x)}">${esc(x.replace(/^\d{4}-0?/,'').replace('-','.'))}</option>`).join('');$('#subjectFilter').value=state.subject;$('#chapterFilter').value=state.chapter;$('#sourceFilter').value=state.source;$('#dateFilter').value=state.date;$('#statusFilter').value=state.status;$('#searchInput').value=state.q}
function renderList(){const arr=filtered();$('#noteCount').textContent=`${arr.length}/${NOTES.length}张`;$('#noteList').innerHTML=arr.length?arr.map(i=>{const s=st(i.id);return `<button class="note-list-card ${state.selected===i.id?'selected':''}" data-note-id="${esc(i.id)}"><span class="read-mark">${s.read?'✓':'○'}</span><span class="note-main"><b>${esc(i.title)}</b><p>${esc(i.subject)} ＞ ${esc(rootTitle(i))} ＞ ${esc(section(i))} ＞ ${esc(i.category||'未分类')}</p><div><span>${esc(source(i))}</span><span>${esc(dateLabel(i))}</span>${s.starred?'<span>重点</span>':''}</div></span><span class="note-arrow">›</span></button>`}).join(''):'<div class="empty"><b>没有匹配笔记</b><p>调整学科、章节或关键词后再试。</p></div>'}
function contentList(i){return uniq([...(i.notebookSummary?.core||[]),...(i.basicExplain||[]),...(i.mustPatterns||[]),...(i.examRefine||[]),...(i.pdfTextLines||[])]).slice(0,35)}
function tokenSet(i){return new Set([i.category,...(i.keywords||[]),...String(i.title||'').split(/[\s·｜—（）()]/)].map(x=>String(x||'').trim()).filter(x=>x.length>=2))}
function relatedKnowledge(note){const a=tokenSet(note);return KNOWLEDGE.filter(i=>i.subject===note.subject&&rootKey(i)===rootKey(note)).map(i=>{const b=tokenSet(i);let score=0;a.forEach(t=>{if(b.has(t)||searchText(i).includes(t.toLowerCase()))score++});if(i.category===note.category)score+=3;if(section(i)===section(note))score+=2;return{i,score}}).filter(x=>x.score>0).sort((x,y)=>y.score-x.score).slice(0,10).map(x=>x.i)}
function renderDetail(){const i=NOTES.find(x=>x.id===state.selected),host=$('#noteDetail');if(!i){host.innerHTML='<div class="empty"><b>选择一篇课堂笔记</b><p>笔记与背诵导图已经彻底分开。</p></div>';return}const s=st(i.id),lines=contentList(i),images=(i.images||[]).slice(0,12),rel=relatedKnowledge(i);host.innerHTML=`<button class="mobile-close" data-close="1">← 返回笔记列表</button><article class="detail-article"><header class="detail-head"><div class="breadcrumb">${esc(i.subject)} ＞ ${esc(rootTitle(i))} ＞ ${esc(section(i))} ＞ ${esc(i.category||'未分类')}</div><h2>${esc(i.title)}</h2><p>${esc(i.oneLine||'课堂过程型资料，用于理解、查阅和复习。')}</p><div class="meta-grid"><span>学科：${esc(i.subject)}</span><span>章：${esc(rootTitle(i))}</span><span>节：${esc(section(i))}</span><span>知识块：${esc(i.category||'未分类')}</span><span>机构：${esc(source(i))}</span><span>导入：${esc(dateLabel(i))}</span><span>类型：${esc(i.recordType||'课堂笔记')}</span></div></header><div class="detail-actions"><button class="primary" data-read="${esc(i.id)}">${s.read?'已看 ✓':'标记已看'}</button><button data-star="${esc(i.id)}">${s.starred?'重点 ✓':'标记重点'}</button><a href="./index.html?item=${encodeURIComponent(i.id)}">进入原笔记卡</a><a href="./memory.html?related=${encodeURIComponent(i.id)}">查看关联知识点</a></div>${lines.length?`<section class="detail-section"><h3>课堂内容整理</h3><ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${images.length?`<section class="detail-section"><h3>课堂原图</h3><div class="detail-images">${images.map(src=>`<a href="${esc(src)}" target="_blank"><img src="${esc(src)}" loading="lazy" alt="课堂原图"></a>`).join('')}</div></section>`:''}<section class="detail-section"><h3>关联背诵知识点</h3><div class="related-grid">${rel.length?rel.map(x=>`<a class="related-card" href="./index.html?item=${encodeURIComponent(x.id)}"><b>${esc(x.title)}</b><span>${esc(x.subject)} ＞ ${esc(rootTitle(x))} ＞ ${esc(x.category||'未分类')}</span></a>`).join(''):'<p>当前没有高置信度匹配的背诵知识点。</p>'}</div></section></article>`;if(matchMedia('(max-width:820px)').matches){host.classList.add('mobile-open');document.body.classList.add('detail-open')}}
function selectNote(id){state.selected=id;data.study||={};data.study[id]={...st(id),read:true,updatedAt:new Date().toISOString()};save();renderList();renderDetail()}
document.addEventListener('click',e=>{const n=e.target.closest('[data-note-id]');if(n){selectNote(n.dataset.noteId);return}if(e.target.closest('[data-close]')){$('#noteDetail').classList.remove('mobile-open');document.body.classList.remove('detail-open');return}const r=e.target.closest('[data-read]');if(r){const id=r.dataset.read;data.study[id]={...st(id),read:!st(id).read,updatedAt:new Date().toISOString()};save();renderList();renderDetail();return}const star=e.target.closest('[data-star]');if(star){const id=star.dataset.star;data.study[id]={...st(id),starred:!st(id).starred,updatedAt:new Date().toISOString()};save();renderList();renderDetail();return}});
['subjectFilter','chapterFilter','sourceFilter','dateFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('change',e=>{const map={subjectFilter:'subject',chapterFilter:'chapter',sourceFilter:'source',dateFilter:'date',statusFilter:'status'};state[map[id]]=e.target.value;if(id==='subjectFilter'){state.chapter='';fillFilters()}state.selected='';renderList();renderDetail()}));let timer;$('#searchInput').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.q=e.target.value.trim();state.selected='';renderList();renderDetail()},180)});
fillFilters();renderList();
const p=new URLSearchParams(location.search),item=p.get('item'),related=p.get('related');if(item&&NOTES.some(i=>i.id===item))selectNote(item);else if(related){const k=ITEMS.find(i=>i.id===related);if(k){const candidates=NOTES.filter(n=>n.subject===k.subject&&rootKey(n)===rootKey(k));if(candidates[0])selectNote(candidates[0].id)}}
