(() => {
  'use strict';
  const V=window.V60;V.setTheme();V.registerSW();
  const notes=V.SORTED.filter(V.isNote).filter(i=>!V.isSourceMaterial(i)),state={subject:'',source:'',status:'',q:'',selected:''};
  const params=new URLSearchParams(location.search);state.selected=params.get('note')||'';const blockParam=params.get('block')||'';
  if(blockParam&&!state.selected){const match=notes.find(i=>V.blockKey(i)===blockParam);if(match)state.selected=match.id;}
  function matches(i){const s=V.state(i.id);if(state.subject&&i.subject!==state.subject)return false;if(state.source&&V.source(i)!==state.source)return false;if(state.status==='unread'&&s.read)return false;if(state.status==='read'&&!s.read)return false;if(state.status==='starred'&&!s.starred)return false;if(state.q){const hay=[i.title,i.oneLine,i.chapter,i.category,...(i.mustPatterns||[]),...(i.basicExplain||[])].join(' ').toLowerCase();if(!hay.includes(state.q.toLowerCase()))return false;}return true;}
  function lines(i){return V.uniq([...(i.basicExplain||[]),...(i.mustPatterns||[]),...(i.examRefine||[]),...(i.memoBlocks||[]).flatMap(x=>Array.isArray(x)?x:[x])].filter(x=>typeof x==='string'&&x.trim())).slice(0,30);}
  function related(i){return V.SORTED.filter(x=>V.isKnowledge(x)&&V.blockKey(x)===V.blockKey(i)).slice(0,8);}
  function renderList(){const rows=notes.filter(matches);V.$('#noteList').innerHTML=rows.length?rows.map(i=>{const s=V.state(i.id);return `<button class="note-item ${state.selected===i.id?'active':''}" data-note="${V.esc(i.id)}"><b>${V.esc(i.title)}</b><span>${V.esc(i.subject)} ＞ ${V.esc(V.chapter(i))} ＞ ${V.esc(V.section(i))}</span><span>${V.esc(i.category||'未分类')} · ${V.esc(V.source(i))} · ${V.esc(V.dateLabel(i))}${s.starred?' · 重点':''}${s.read?' · 已看':''}</span></button>`}).join(''):'<div class="empty">没有符合条件的课堂笔记。</div>';}
  function renderDetail(){const i=V.BY_ID.get(state.selected),host=V.$('#noteDetail');if(!i||!V.isNote(i)){host.innerHTML='<div class="empty">选择一篇课堂笔记。</div>';return}const s=V.state(i.id),content=lines(i),rel=related(i);host.innerHTML=`<button class="ghost-btn mobile-back" data-close-note>← 返回笔记列表</button><div class="path">${V.esc(i.subject)} ＞ ${V.esc(V.chapter(i))} ＞ ${V.esc(V.section(i))} ＞ ${V.esc(i.category||'未分类')}</div><h2>${V.esc(i.title)}</h2><p>${V.esc(i.oneLine||'课堂过程型资料，用于理解和查阅。')}</p><div class="meta-grid"><span>学科：${V.esc(i.subject)}</span><span>章：${V.esc(V.chapter(i))}</span><span>节：${V.esc(V.section(i))}</span><span>知识块：${V.esc(i.category||'未分类')}</span><span>来源：${V.esc(V.source(i))}</span><span>导入：${V.esc(V.dateLabel(i))}</span></div><div class="detail-actions"><button data-read="${V.esc(i.id)}" class="${s.read?'active':''}">${s.read?'已看 ✓':'标记已看'}</button><button data-star="${V.esc(i.id)}" class="${s.starred?'active':''}">${s.starred?'重点 ✓':'标记重点'}</button><a href="./library.html?item=${encodeURIComponent(i.id)}">完整原笔记</a></div>${content.length?`<section><h3>课堂内容整理</h3><ul>${content.map(x=>`<li>${V.esc(x)}</li>`).join('')}</ul></section>`:''}${i.images?.length?`<section><h3>课堂原图</h3><div class="detail-images">${i.images.slice(0,16).map(src=>`<a href="${V.esc(src)}" target="_blank"><img src="${V.esc(src)}" loading="lazy" alt="课堂原图"></a>`).join('')}</div></section>`:''}<section><h3>关联背诵知识点</h3><div class="item-links">${rel.length?rel.map(x=>`<a href="./library.html?item=${encodeURIComponent(x.id)}"><b>${V.esc(x.title)}</b><span>${V.esc(x.category||'未分类')}</span></a>`).join(''):'<p>当前没有高置信度关联知识点。</p>'}</div></section>`;if(matchMedia('(max-width:820px)').matches)host.classList.add('mobile-open');}
  function rerender(){renderList();renderDetail();}
  document.addEventListener('click',e=>{const n=e.target.closest('[data-note]');if(n){state.selected=n.dataset.note;rerender();return}const r=e.target.closest('[data-read]');if(r){const s=V.state(r.dataset.read);V.updateState(r.dataset.read,{read:!s.read});rerender();return}const st=e.target.closest('[data-star]');if(st){const s=V.state(st.dataset.star);V.updateState(st.dataset.star,{starred:!s.starred});rerender();return}if(e.target.closest('[data-close-note]')){V.$('#noteDetail').classList.remove('mobile-open');}});
  V.$('#noteSubject').addEventListener('change',e=>{state.subject=e.target.value;renderList()});V.$('#noteSource').addEventListener('change',e=>{state.source=e.target.value;renderList()});V.$('#noteStatus').addEventListener('change',e=>{state.status=e.target.value;renderList()});let t;V.$('#noteSearch').addEventListener('input',e=>{clearTimeout(t);t=setTimeout(()=>{state.q=e.target.value.trim();renderList()},160)});
  if(!state.selected){const first=notes.find(matches);if(first)state.selected=first.id;}rerender();
})();
