(() => {
  'use strict';
  const V=window.V60;V.setTheme();V.registerSW();const questions=V.SORTED.filter(V.isQuestion),state={subject:'',status:'',q:'',block:new URLSearchParams(location.search).get('block')||''};
  const requested=new URLSearchParams(location.search).get('item');
  function matches(i){const s=V.state(i.id);if(state.subject&&i.subject!==state.subject)return false;if(state.block&&V.blockKey(i)!==state.block)return false;if(state.status==='unanswered'&&(s.read||s.mastered||s.wrong))return false;if(state.status==='wrong'&&!s.wrong)return false;if(state.status==='correct'&&!s.mastered)return false;if(state.q){const hay=[i.title,i.problem,i.oneLine,i.chapter,i.category,...(i.keywords||[])].join(' ').toLowerCase();if(!hay.includes(state.q.toLowerCase()))return false;}return true;}
  function render(){const rows=questions.filter(matches),host=V.$('#questionList');host.innerHTML=rows.length?rows.map(i=>{const s=V.state(i.id);return `<article id="q-${V.esc(i.id)}" class="question-card ${s.wrong?'wrong':s.mastered?'correct':''}"><div class="path">${V.esc(i.subject)} ＞ ${V.esc(V.chapter(i))} ＞ ${V.esc(V.section(i))} ＞ ${V.esc(i.category||'未分类')}</div><h3>${V.esc(i.title)}</h3>${V.questionHtml(i)}<div id="ans-${V.esc(i.id)}" class="answer-box">${V.answerHtml(i)}</div><div class="question-actions"><button data-reveal="${V.esc(i.id)}">核对答案</button><button class="wrong-btn" data-qgrade="0" data-id="${V.esc(i.id)}">做错了</button><button class="correct-btn" data-qgrade="2" data-id="${V.esc(i.id)}">做对了</button><a href="./library.html?item=${encodeURIComponent(i.id)}">完整解析与原图</a><a href="./knowledge.html?search=${encodeURIComponent(i.category||'')}">返回知识块</a></div></article>`}).join(''):'<div class="empty">没有符合条件的题目。</div>';if(requested){setTimeout(()=>document.getElementById(`q-${requested}`)?.scrollIntoView({behavior:'smooth',block:'start'}),50)}}
  document.addEventListener('click',e=>{const r=e.target.closest('[data-reveal]');if(r){document.getElementById(`ans-${r.dataset.reveal}`)?.classList.toggle('open');return}const g=e.target.closest('[data-qgrade]');if(g){const i=V.BY_ID.get(g.dataset.id);V.markGrade(i,Number(g.dataset.qgrade));render();}});
  V.$('#qSubject').addEventListener('change',e=>{state.subject=e.target.value;render()});V.$('#qStatus').addEventListener('change',e=>{state.status=e.target.value;render()});let t;V.$('#qSearch').addEventListener('input',e=>{clearTimeout(t);t=setTimeout(()=>{state.q=e.target.value.trim();render()},160)});render();
})();
